// Centralized async loader for iteration components.
//
// `iterations/index.ts` is auto-regenerated by the server/agent as new
// iteration files land (see server/routes/iterations.ts `regenerateIndex`).
// A static import can serve an in-memory copy captured before the file was last
// regenerated. A dynamic `import()` re-resolves the module each call.

export async function loadIterationComponentModule(): Promise<{
  getIterationComponent: (filename: string) => React.ComponentType<any> | undefined;
}> {
  try {
    return await import('@pg/iterations');
  } catch {
    return { getIterationComponent: () => undefined };
  }
}
