// Centralized loader for on-canvas JSX components.
// Uses a relative path so the playground can be embedded into
// other Next.js applications without relying on host-specific aliases.
// The index barrel is auto-generated by the server when components are
// written — until then the module does not exist, so handle that gracefully.

export async function loadOnCanvasComponentModule(): Promise<{
  canvasComponents: Record<string, React.ComponentType<any>>;
  getOnCanvasComponent: (filename: string) => React.ComponentType<any> | undefined;
}> {
  try {
    return await import('../canvas-components/index');
  } catch {
    return {
      canvasComponents: {},
      getOnCanvasComponent: () => undefined,
    };
  }
}

